version: 2
sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: ventes_brut_gwz
        description: les ventes réalisées par Greenweez

      - name: products
        identifier: produits_brut_gwz
        tests:
          - unique: 
               column_name: products_id
          - not_null: 
               column_name: products_id

      - name: ship
        identifier: navire_brut_gwz
        description: ship cost de Greenweez
        tests:
          - unique: 
                column_name: orders_id
          - not_null: 
                column_name: orders_id

      - name: adwords
        identifier: raw_gz_adwords
        tests:
          - unique: 
                column_name: "(date_date || '_' || campaign_key)"
          - not_null: 
                column_name: "(date_date || '_' || campaign_key)"


      - name: bing
        identifier: raw_gz_bing
        tests:
          - unique: 
                column_name: "(date_date || '_' || campaign_key)"
          - not_null: 
                column_name: "(date_date || '_' || campaign_key)"

      - name: criteo
        identifier: raw_gz_criteo
        tests:
          - unique: 
                column_name: "(date_date || '_' || campaign_key)"
          - not_null: 
                column_name: "(date_date || '_' || campaign_key)"

      - name: facebook
        identifier: raw_gz_facebook
        tests:
          - unique: 
                column_name: "(date_date || '_' || campaign_key)"
          - not_null: 
                column_name: "(date_date || '_' || campaign_key)"

              
              

  